tasks:
  - init: npm install
    command: npm run start
# Ports to expose on workspace startup (optional)
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - vscodevim.vim@1.12.4:nIIc71K1blhNiazHIBCo+Q==